require 'lib/game/modules/object_management'
require 'lib/game/modules/try_helper'
require 'lib/game/modules/array_sum'
require 'lib/game/modules/instance_setter'
require 'lib/game/modules/impassible'